root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT1000To1500.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT100To200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT1500To2000.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT2000Toinf.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT200To300.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT300To500.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT500To700.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/QCDHT700To1000.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/ST.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/SaT.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/TT.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJets.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetsToQQ_HT-600ToInf.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WW.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WZ.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/ZZ.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_1200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_1400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_1600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_1800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_2000.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_2200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_2400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_2600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_2800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_3000.root")'   
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_1200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_1400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_1600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_1800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_2000.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_2200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_2400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_2600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_2800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_3000.root")'    


root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT70To100.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT100To200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT200To400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT400To600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT600To800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT800To1200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT1200To2500.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/WJetHT2500ToInf.root")'


root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_3200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_3400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_3600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_3800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_4000.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/RH_4200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_3200.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_3400.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_3600.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_3800.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_4000.root")'
root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_EleQCDCR/LH_4200.root")'

#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/RH_3200.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/RH_3400.root")'  
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/RH_3600.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/RH_3800.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/RH_4000.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/RH_4200.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/LH_3200.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/LH_3400.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/LH_3600.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/LH_3800.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/LH_4000.root")'
#root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_MuonTTCR/LH_4200.root")'
#
#
#
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/RH_3200.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/RH_3400.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/RH_3600.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/RH_3800.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/RH_4000.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/RH_4200.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/LH_3200.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/LH_3400.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/LH_3600.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/LH_3800.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/LH_4000.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Muonchannel/LH_4200.root")'
# 
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/RH_3200.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/RH_3400.root")'  
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/RH_3600.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/RH_3800.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/RH_4000.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/RH_4200.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/LH_3200.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/LH_3400.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/LH_3600.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/LH_3800.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/LH_4000.root")'
# root -l -b -q  sumfile.cc+'("/afs/ihep.ac.cn/users/p/pengn/WorkSpace/FullRunIIdataV2/tWIHEPFramework/config/weights/2016data/BTag_eff_Elechannel/LH_4200.root")' 
